### PR TITLE
Support AndroidX

### PR DESCRIPTION
**Pull request by yudaprama**
When I build with `flutter build apk`, I’ve got following error:

```
* What went wrong:
Execution failed for task ':flutter_facebook_login:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/yuda/coin/build/flutter_facebook_login/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/yuda/coin/build/flutter_facebook_login/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/yuda/coin/build/flutter_facebook_login/intermediates/res/merged/release/values/values.xml:2779: error: resource android:attr/fontVariationSettings not found.
  /Users/yuda/coin/build/flutter_facebook_login/intermediates/res/merged/release/values/values.xml:2780: error: resource android:attr/ttcIndex not found.
  error: failed linking references
```

This commit fix it

### CODE REVIEW

**Comment by ened** [comment]
@yudaprama, nice PR!

Could you please update:
 - gradle version to 4.10.2
 - increment version by a major step (=> 1.3.0)
 - update change log
?

**Comment by yudaprama** [comment]
@ened I have updated. Please review again

**Comment by ened** [comment]
Nice. @roughike, ok to merge?

**Comment by MrWaggel** [comment]
Any updates on this?

Also do you need to do step 3 form:  
https://developers.facebook.com/docs/facebook-login/android

**Comment by yudaprama** [comment]
No, you don't

**Comment by DennisdeBest** [comment]
Hey guys any news on when this will be merged ? Thanks for the work you have put in so far, it works fine on IoS

**Comment by ened** [comment]
As we are not sure when this will be merged, you can adjust your `pubspec.yaml` in the meantime:

```
dependency_overrides:
  flutter_facebook_login:
    git: 
      url: https://github.com/yudaprama/flutter_facebook_login
      ref: android-x
```

**Comment by LatinaIsaac** [comment]
waiting 4 merge

**Comment by maattdd** [comment]
It is a breaking change, the version should bump to 2.0.0 and not 1.3.0 (I think this package respects semver).

**Comment by JeffScaturro** [comment]
Thanks for the work @yudaprama! 

Though @maattdd  is right, this should be a major change, right now it's PR'd as a minor change (major.minor.patch). Flutter [recommends it](https://flutter.io/docs/development/packages-and-plugins/androidx-compatibility#for-plugin-maintainers-migrating-a-flutter-plugin-to-androidx) as well.

**Comment by roughike** [comment]
Thanks, I'll review ASAP and update some docs regarding this change. Expecting a release this week.

**Comment by AppleEducate** [comment]
This is breaking my apps too, thanks for the PR @yudaprama

**Comment by roughike** [comment]
Thanks for the effort and sorry for being slow to review!

I decided to go with #96 instead, as that one was closer to how the official Flutter plugins were migrated to AndroidX. Seems like that approach also works better for libraries that doesn't have AndroidX support just yet.

I would love people to test this and verify that it works for you too. If everything is fine, I'll make a new major release on Pub in a couple days. Follow [these instructions to migrate your Flutter app to AndroidX](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#how-to-migrate-a-flutter-app-to-androidx) and then include the AndroidX -compatible `flutter_facebook_login` like this:

```yaml
dependencies:
  flutter_facebook_login:
    git:
      url: https://github.com/roughike/flutter_facebook_login
      ref: e69fef3
```

**Comment by AppleEducate** [comment]
Awesome thanks!

**Pull request closed without merging**
